sudo: required
services:
  - docker

before_install:
  - docker build -t devendra0307/docker-react -f dockerfile.dev .

script:
   - docker run -e CI=true devendra0307/docker-react npm run test -- --coverage